### ISSUE TITLE
Media copy error if destination folder does not exists

### ISSUE THREAD

**Issue by igorsKolcinsMagebit** [magebitcom/magento2-configurator#14]
Configurator does not copy image and throws and error if destination folder do not exists
![image](https://github.com/magebitcom/magento2-configurator/assets/46994993/ab7a4daf-9e35-483b-ac19-60106aaa76b0)
Like we are trying to place image into pub/media/wysiwyg/icons, and icons does not eixsts
Easy fix is to manually create "icons" dir

Need to implement smth like this in file Component/Media.php:138
```
if (!is_dir('upload/promotions/' . $month)) {
  // dir doesn't exist, make it
  mkdir('upload/promotions/' . $month);
}

file_put_contents('upload/promotions/' . $month . '/' . $image, $contents_data);
```

**Comment by rf-helenoftroy** [comment]
Not an issue. 


❌ Wrong
```
wysiwyg:
  - name: test/image.jpg
    location: app/etc/configurator/Media/content/wysiwyg/test/image.jpg
```
**Explanation**: script is not parsing name to find folder. Meaning, the script will think that the image name is `test/image.jpg`, and will try to use it in `file_put_contents()`. If `test` folder is not created, an exception will be thrown.

---

✅ Correct
```
wysiwyg:
  test:
    - name: image.svg
       location: app/etc/configurator/Media/content/wysiwyg/test/image.jpg
```
**Explanation**: script will see that `wysisyg` have child directory `test` and will create it before copying the image.

---

⚠️ Warning
In cases when we need to have image in parent and child folders, we need to split YAML file into two files:
File 1:
```
wysiwyg:
  - name: test1/image1.jpg
    location: app/etc/configurator/Media/content/wysiwyg/test/image1.jpg
```
File 2:
```
wysiwyg:
  test2:
    - name: image2.svg
       location: app/etc/configurator/Media/content/wysiwyg/test/image2.jpg
```
**Explanation:** In YAML we have arrays (it's called Sequences) and nasting (called nested block).
You cannot mix Sequences and nasted block like that:
```
wysiwyg:
  - name: test1/image1.jpg
    location: app/etc/configurator/Media/content/wysiwyg/test/image1.jpg
  test2:
    - name: image2.svg
       location: app/etc/configurator/Media/content/wysiwyg/test/image2.jpg
```
Because YAML will parse test2 as an property of first image.
Seconcd way will not work eathier:
```
wysiwyg:
  - name: test1/image1.jpg
    location: app/etc/configurator/Media/content/wysiwyg/test/image1.jpg
  - test2:
    - name: image2.svg
       location: app/etc/configurator/Media/content/wysiwyg/test/image2.jpg
```
This way test 2 will be an array element which contains object with 2nd image.
YAML guideline: https://dev.to/kalkwst/a-gentle-introduction-to-the-yaml-format-bi6

**Comment by igorsKolcinsMagebit** [comment]
Not an issue. 


❌ Wrong
```
wysiwyg:
  - name: test/image.jpg
    location: app/etc/configurator/Media/content/wysiwyg/test/image.jpg
```
**Explanation**: script is not parsing name to find folder. Meaning, the script will think that the image name is `test/image.jpg`, and will try to use it in `file_put_contents()`. If `test` folder is not created, an exception will be thrown.

---

✅ Correct
```
wysiwyg:
  test:
    - name: image.svg
       location: app/etc/configurator/Media/content/wysiwyg/test/image.jpg
```
**Explanation**: script will see that `wysisyg` have child directory `test` and will create it before copying the image.

---

⚠️ Warning
In cases when we need to have image in parent and child folders, we need to split YAML file into two files:
File 1:
```
wysiwyg:
  - name: test1/image1.jpg
    location: app/etc/configurator/Media/content/wysiwyg/test/image1.jpg
```
File 2:
```
wysiwyg:
  test2:
    - name: image2.svg
       location: app/etc/configurator/Media/content/wysiwyg/test/image2.jpg
```
**Explanation:** In YAML we have arrays (it's called Sequences) and nasting (called nested block).
You cannot mix Sequences and nasted block like that:
```
wysiwyg:
  - name: test1/image1.jpg
    location: app/etc/configurator/Media/content/wysiwyg/test/image1.jpg
  test2:
    - name: image2.svg
       location: app/etc/configurator/Media/content/wysiwyg/test/image2.jpg
```
Because YAML will parse test2 as an property of first image.
Seconcd way will not work eathier:
```
wysiwyg:
  - name: test1/image1.jpg
    location: app/etc/configurator/Media/content/wysiwyg/test/image1.jpg
  - test2:
    - name: image2.svg
       location: app/etc/configurator/Media/content/wysiwyg/test/image2.jpg
```
This way test 2 will be an array element which contains object with 2nd image.
YAML guideline: https://dev.to/kalkwst/a-gentle-introduction-to-the-yaml-format-bi6
